In [1]:
import numpy as np

In [2]:
import math

In [3]:
a = np.array([1,2,3,4])

In [4]:
a

array([1, 2, 3, 4])

In [5]:
a1 = np.array([[1,2,3],[4,5,6]])
a1

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
a3 = np.array([[[2,3]],[[4,5]]])
a3

array([[[2, 3]],

       [[4, 5]]])

In [9]:
c = np.arange(1,11,2)

In [10]:
c

array([1, 3, 5, 7, 9])

In [11]:
d = np.arange(16).reshape(2,2,2,2)

In [12]:
d

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

In [14]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [15]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [16]:
a1.ndim

2

In [17]:
a.ndim

1

In [18]:
a3.ndim

3

In [19]:
print(a1.shape)

(2, 3)


In [20]:
print(d.shape)

(2, 2, 2, 2)


In [23]:
a1.itemsize

4

In [38]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(4,3)

In [28]:
print(a1)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [29]:
print(a2)

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [30]:
a1**2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [31]:
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [33]:
a1 == 6

array([[False, False, False, False],
       [False, False,  True, False],
       [False, False, False, False]])

In [36]:
print(a1)
print(a1.shape)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
(3, 4)


In [39]:
print(a2)
print(a2.shape)

[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]
(4, 3)


In [40]:
t = np.dot(a1,a2)

In [41]:
t

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [47]:
np.floor(np.random.random((2,3))*100)

array([[86., 15., 44.],
       [84., 70., 41.]])